server:
  port: 8081
api.url.inventory: http://localhost:8080/inventory/
spring:
  application:
    name: store-service
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true
