server.port: 8091
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: docker
  application:
    name: inventory-service
  cloud:
    stream:
      kafka:
        bindings:
          stockChannel:
            consumer:
              ackEachRecord: true
      default:
        group: 'inventoryServiceGroup'
      bindings:
        stockChannel:
          destination: PRODUCT_STOCK
security:
  jwt:
    public-key: classpath:public.txt
