server.port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://db:5432/ms
    username: ms
    password: ms
  application:
    name: inventory-service
  cloud:
    stream:
      kafka:
        bindings:
          stockChannel:
            consumer:
              ackEachRecord: true
      default:
        group: 'inventoryServiceGroup'
      bindings:
        stockChannel:
          destination: ${PRODUCT_STOCK_CHANNEL:PRODUCT_STOCK}
security:
  jwt:
    public-key: classpath:public.txt
