server.port: 8999

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
        - id: checkout
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          filters:
            - StripPrefix=1
  application:
    name: gateway-service

